# Generated by Django 5.1.7 on 2025-07-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('depot_id', models.AutoField(primary_key=True, serialize=False)),
                ('depot_name', models.CharField(max_length=100)),
                ('depot_code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepotUser',
            fields=[
                ('depot_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.depot')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('conductor', 'Conductor'), ('driver', 'Driver')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.depot')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_no', models.CharField(max_length=20)),
                ('trip_no', models.IntegerField()),
                ('route_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.depotuser')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.employee')),
            ],
            options={
                'unique_together': {('employee', 'date', 'schedule_no', 'trip_no')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='absent', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.depotuser')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot_portal.employee')),
                ('schedule_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='depot_portal.scheduleassignment')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
