# Generated by Django 5.1.7 on 2025-07-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'schedule_assignment')},
        ),
    ]
