# Generated by Django 5.1.7 on 2025-07-07 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_date', models.DateField(default=datetime.date.today)),
                ('best_performing_routes', models.JSONField(default=list)),
                ('underperforming_routes', models.JSONField(default=list)),
                ('total_routes_analyzed', models.IntegerField(default=0)),
                ('industry_avg_epkm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('comparison_date',)},
            },
        ),
        migrations.CreateModel(
            name='RoutePerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20)),
                ('date_range', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('avg_epkm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trip_count', models.IntegerField(default=0)),
                ('performance_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['route_no', 'date_range'], name='route_perfo_route_n_064128_idx'), models.Index(fields=['avg_epkm'], name='route_perfo_avg_epk_419f5d_idx'), models.Index(fields=['performance_rank'], name='route_perfo_perform_4a9e3a_idx')],
                'unique_together': {('route_no', 'date_range', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='RoutePerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('epkm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trip_count', models.IntegerField()),
                ('epkm_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('performance_category', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['route_no', 'date'], name='route_perfo_route_n_506a60_idx'), models.Index(fields=['epkm_trend'], name='route_perfo_epkm_tr_89eba6_idx')],
                'unique_together': {('route_no', 'date')},
            },
        ),
    ]
