# Generated by Django 5.1.7 on 2025-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusOverlapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20)),
                ('schedule_no', models.CharField(max_length=20)),
                ('trip_no', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('route_no', 'schedule_no', 'trip_no')},
            },
        ),
        migrations.CreateModel(
            name='RouteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(max_length=20)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('time_period_start', models.TimeField()),
                ('time_period_end', models.TimeField()),
                ('total_buses', models.IntegerField(default=0)),
                ('overlap_score', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('route_no', 'time_period_start', 'time_period_end')},
            },
        ),
    ]
