# Generated by Django 5.1.7 on 2025-07-05 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busoverlapdata',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routeanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='busoverlapdata',
            name='selected_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='routeanalysis',
            name='selected_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='busoverlapdata',
            unique_together={('route_no', 'schedule_no', 'trip_no', 'selected_date')},
        ),
        migrations.AlterUniqueTogether(
            name='routeanalysis',
            unique_together={('route_no', 'selected_date', 'time_period_start', 'time_period_end')},
        ),
    ]
