# Generated by Django 5.1.7 on 2025-07-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_busoverlapdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busoverlapdata',
            name='estimated_passengers',
            field=models.IntegerField(default=0),
        ),
    ]
